export const LINK_CONSTRAINTS = {
  SHORTCODE_MAX_LENGTH: 255,
  SHORTCODE_REGEX: /^[a-zA-Z0-9-_]+$/,

  TITLE_MAX_LENGTH: 255,

  MAX_EXPIRATION_YEARS: 5,

  UTM_SOURCE_MAX_LENGTH: 100,
  UTM_MEDIUM_MAX_LENGTH: 100,
  UTM_CAMPAIGN_MAX_LENGTH: 100,
  UTM_CONTENT_MAX_LENGTH: 100,
  UTM_TERM_MAX_LENGTH: 100,
};
